apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiga.fullname" . }}-async
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.async.type | default "ClusterIP" }}
  {{- if .Values.service.async.port }}
  ports:
    - name: {{ .Values.service.async.name | default "http" }}
      port: {{ .Values.service.async.port }}
      targetPort: {{ .Values.service.async.targetport }}
      protocol: {{ .Values.service.async.protocol | default "TCP" }}
  {{- end }}
  selector:
    {{- include "taiga.selectorLabels" . | nindent 4 }}
