{{- $name := include "taiga.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-back
  labels:
    {{ include "taiga.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "taiga.selectorLabels" . | nindent 6 }}
  template:
    metadata:
  labels:
    {{ include "taiga.selectorLabels" . | nindent 8 }}
  annotations:
    {{ toYaml .Values.podAnnotations | indent 8 }}
    spec:
  serviceAccountName: {{ include "taiga.serviceAccountName" . }}
  {{- if .Values.imagePullSecrets }}
  imagePullSecrets:
    {{ toYaml .Values.imagePullSecrets | indent 8 }}
  {{- end }}
  containers:
	  - name: taiga-back
	    image: "{{ .Values.back.image.repository }}:{{ .Values.back.image.tag }}"
	    imagePullPolicy: {{ .Values.back.image.pullPolicy }}
	    ports:
        - name: http
          containerPort: 8000
      env:
        {{- if .Values.back.env }}
        {{ toYaml .Values.back.env | indent 12 }}
        {{- end }}
	    volumeMounts:
        {{- if .Values.back.volumeMounts }}
        {{ toYaml .Values.back.volumeMounts | indent 12 }}
        {{- end }}
	    livenessProbe:
        {{ toYaml .Values.livenessProbe | indent 12 }}
	    readinessProbe:
        {{ toYaml .Values.readinessProbe | indent 12 }}
	    resources:
        {{ toYaml .Values.resources | indent 12 }}
	volumes:
    {{- if .Values.back.volumes }}
    {{ toYaml .Values.back.volumes | indent 8 }}
    {{- end }}
	nodeSelector:
    {{ toYaml .Values.nodeSelector | indent 8 }}
	tolerations:
    {{ toYaml .Values.tolerations | indent 8 }}
	affinity:
    {{ toYaml .Values.affinity | indent 8 }}

