{{- $name := include "taiga.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-gateway
  labels:
    {{ include "taiga.labels" . | nindent 4 }}
    app: gateway
spec:
  replicas: {{ default .Values.replicaCount .Values.gateway.replicas }}
  selector:
    matchLabels:
      {{ include "taiga.selectorLabels" . | nindent 6 }}
      app: gateway
  template:
    metadata:
      labels:
        {{ include "taiga.selectorLabels" . | nindent 8 }}
        app: gateway
      annotations:
        {{ toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ include "taiga.serviceAccountName" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: taiga-gateway
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ default 80 .Values.gateway.containerPort }}
          env:
            {{- if .Values.gateway.env }}
            {{ toYaml .Values.gateway.env | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.gateway.volumeMounts }}
            {{ toYaml .Values.gateway.volumeMounts | nindent 12 }}
            {{- end }}
            - name: config
              mountPath: "/etc/nginx/conf.d/default.conf"
              subPath: "default.conf"
              readOnly: true
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.gateway.volumes }}
        {{ toYaml .Values.gateway.volumes | nindent 8 }}
        {{- end }}
        - name: config
          configMap:
            name: {{ include "taiga.fullname" . }}-gateway
            items:
              - key: "default.conf"
                path: "default.conf"
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{ toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{ toYaml .Values.affinity | nindent 8 }}
